openresty:
  enabled: true
  image:
    repository: docker.io/openresty/openresty
    tag: "1.21.4.1-0-alpine"

  domain: 'http://172.31.19.4:32080'
  authentication:
    enabled: true
    blacklist: 
      - admin@kubesphere.io

  service:
    type: NodePort
    portNumber: 80
    nodePort: 32080
    annotations: {}

  configs:
    #- name: alertmanager
    #  description: KubeSphere 监控栈内部 Alertmanager 端点
    #  subPath: /alertmanager/
    #  endpoint: http://whizard-notification-alertmanager.kubesphere-monitoring-system.svc:9093/
    #  additional:
    #   proxy_set_header Host $host;
    #   proxy_set_header X-Real-IP $remote_addr;
    #- name: prometheus
    #  description: KubeSphere 监控栈内部 Prometheus 端点
    #  subPath: /prometheus/
    #  endpoint: http://prometheus-agent-operated.kubesphere-monitoring-system.svc:9090/
    #  additional:
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Real-IP $remote_addr;
    #- name: whizard
    #  description: KubeSphere 监控栈内部 Whizard Query UI
    #  subPath: /whizard/
    #  endpoint: http://query-frontend-whizard-operated.kubesphere-monitoring-system.svc:10902/
    #  additional:
    #    proxy_set_header X-Forwarded-Prefix /whizard;
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Real-IP $remote_addr;

oauth2-proxy:
  enabled: true
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: ""
  config:
    # OAuth client ID
    clientID: "oauth2-proxy"
    # OAuth client secret
    clientSecret: "oauth2-proxy"
    # Create a new secret with the following command
    # openssl rand -base64 32 | head -c 32 | base64
    # Use an existing secret for OAuth2 credentials (see secret.yaml for required fields)
    # Example:
    # existingSecret: secret
    cookieSecret: "IwwLQh_8mE-tRjgLmOhoqiBhQIL6AaRFNXRT9zopNG8="

  extraArgs:
    provider: oidc
    provider-display-name: "ks-apiserver"
    cookie-secure: false
    cookie-refresh: 1m
    cookie-expire: 30m
    cookie-name: oauth2-proxy
    cookie-csrf-expire: 15m
    cookie-csrf-per-request: true
    set-xauthrequest: true
    upstream: http://oauth2-proxy-openresty.extension-oauth2-proxy.svc:80/
    exclude-logging-path: "/ping,/ready"
    # issuer address
    oidc-issuer-url: http://172.31.19.4:30880    
    # service redirect address
    redirect-url: http://172.31.19.4:32080/oauth2/callback

  service:
    type: ClusterIP
    portNumber: 4180

  # whether to use http or https
  httpScheme: http

  extraVolumes: []
  # mount tls certs
  # - name: tls-cert
  #   secret:
  #     secretName: oauth2-proxy-tls-assets

  extraVolumeMounts: []
  # mount tls certs
  # - mountPath: /etc/oauth2-proxy/certs/
  #   name: tls-cert