apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openresty.fullname" . }}-index 
  labels:
    {{- include "openresty.labels" . | nindent 4 }}
data: 
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Oauth2-Proxy</title>
      <style>
        h3 {
          margin-left: 25px; /* 标题向右移动 25px */
        }
        table {
          border-collapse: collapse;
          width: calc(100% - 50px); /* 减去左右两侧边距的宽度 */
          margin-left: 25px; /* 左侧边距 */
          margin-right: 25px; /* 右侧边距 */
        }
        th, td {
          border: 1px solid black;
          padding: 8px;
          text-align: left;
        }
        th {
          background-color: #f2f2f2;
        }
      </style>
      <script>
        var currentUrl = window.location.href;
    
        // 获取所有带有 "dynamic-link" 类的链接元素
        var links = document.getElementsByClassName("dynamic-link");
      
        // 遍历链接元素并设置 href 属性
        for (var i = 0; i < links.length; i++) {
          var link = links[i];
          var path = link.getAttribute("href"); // 获取链接的路径
      
          // 构建完整的 URL
          var url = currentUrl.substring(0, currentUrl.lastIndexOf("/") + 1) + path;
      
          // 将 URL 设置为链接的 href 属性
          link.href = url;
        }
      </script>
    </head>
    <body>
      <h3>oauth2-proxy 服务代理列表:</h3>
      <table>
        <tr>
          <th>Service</th>
          <th>Description</th>
          <th>Link</th>
        </tr>
{{- range .Values.configs }}
        <tr>
          <td><a class="dynamic-link" href="{{ .subPath }}">{{ .name }}</a></td>
          <td>{{ .description }}</td>
          <td><a class="dynamic-link" href="{{ .subPath }}">{{ .subPath }}</a></td>
        </tr>
{{- end }}
      </table>
    </body>
    </html>